import uuid from 'uuid/v4';

let ids = Array(20).fill(null);

ids = ids.map(() => uuid());

export default {
  [ids[0]]: {
    id: ids[0],
    title: 'DD1334 Database Technology',
    desc:
      'A continuation in computer science that covers the fundamentals of database technology.',
    type: 'root',
    state: 'auto',
    links: [],
    estimate: 1,
  },
  [ids[1]]: {
    id: ids[1],
    title: 'Learning Goal 1',
    desc: 'Schema and queries in relational database model using SQL',
    type: 'template',
    state: 'auto',
    links: [ids[0]],
    estimate: 1,
  },
  [ids[2]]: {
    id: ids[2],
    title: 'Learning Goal 2',
    desc:
      'The operation of constraints and triggers during  modifications of a SQL database',
    type: 'template',
    state: 'auto',
    links: [ids[0]],
    estimate: 1,
  },
  [ids[3]]: {
    id: ids[3],
    title: 'Learning Goal 3',
    desc:
      'How to avoid anomalies, preserve information and dependencies in the design of a relational databases',
    type: 'template',
    state: 'auto',
    links: [ids[0]],
    estimate: 1,
  },
  [ids[4]]: {
    id: ids[4],
    title: 'Learning Goal 4',
    desc:
      'The use of ER diagrams and design principles in relational database design',
    type: 'template',
    state: 'auto',
    links: [ids[0]],
    estimate: 1,
  },
  [ids[5]]: {
    id: ids[5],
    title: 'Learning Goal 5',
    desc: 'The XML database model, XML-schema DTD, and XQuery',
    type: 'template',
    state: 'auto',
    links: [ids[0]],
    estimate: 1,
  },
  [ids[6]]: {
    id: ids[6],
    title: 'Relational algebra',
    desc: 'I need to read about this subject and learn more',
    type: 'task',
    state: 'todo',
    links: [ids[1], ids[2], ids[4]],
    estimate: 1,
  },
  [ids[7]]: {
    id: ids[7],
    title: 'XML databases',
    desc: 'I need to read about this subject and learn more',
    type: 'task',
    state: 'todo',
    links: [ids[5]],
    estimate: 1,
  },
  [ids[8]]: {
    id: ids[8],
    title: 'Computer Lab 1',
    desc: 'Description of the task',
    type: 'task',
    state: 'inProgress',
    links: [ids[1], ids[4]],
    estimate: 1,
  },
  [ids[9]]: {
    id: ids[9],
    title: 'Computer Lab 2',
    desc: 'Description of the task',
    type: 'task',
    state: 'inProgress',
    links: [ids[2], ids[4]],
    estimate: 1,
  },
  [ids[10]]: {
    id: ids[10],
    title: 'Computer Lab 3',
    desc: 'Description of the task',
    type: 'task',
    state: 'todo',
    links: [ids[2], ids[3]],
    estimate: 1,
  },
  [ids[11]]: {
    id: ids[11],
    title: 'Computer Lab 4',
    desc: 'Description of the task',
    type: 'task',
    state: 'todo',
    links: [ids[3], ids[5]],
    estimate: 1,
  },
  [ids[12]]: {
    id: ids[12],
    title: 'Prepare Computer Lab 2',
    desc: 'Description of the task',
    type: 'task',
    state: 'done',
    links: [ids[9]],
    estimate: 1,
  },
  [ids[13]]: {
    id: ids[13],
    title: 'Prepare Computer Lab 3',
    desc: 'Description of the task',
    type: 'task',
    state: 'todo',
    links: [ids[10]],
    estimate: 1,
  },
  [ids[14]]: {
    id: ids[14],
    title: 'Prepare Computer Lab 4',
    desc: 'Description of the task',
    type: 'task',
    state: 'done',
    links: [ids[11]],
    estimate: 1,
  },
  [ids[15]]: {
    id: ids[15],
    title: 'Computer Lab 5',
    desc: 'Description of the task',
    type: 'task',
    state: 'todo',
    links: [ids[3]],
    estimate: 1,
  },
  [ids[16]]: {
    id: ids[16],
    title: 'Prepare Computer Lab 5',
    desc: 'Description of the task',
    type: 'task',
    state: 'todo',
    links: [ids[15]],
    estimate: 1,
  },
  [ids[17]]: {
    id: ids[17],
    title: 'Computer Lab 5 - part A',
    desc: 'Description of the task',
    type: 'task',
    state: 'todo',
    links: [ids[15]],
    estimate: 1,
  },
  [ids[18]]: {
    id: ids[18],
    title: 'Computer Lab 5 - part B',
    desc: 'Description of the task',
    type: 'task',
    state: 'todo',
    links: [ids[15]],
    estimate: 1,
  },
  [ids[19]]: {
    id: ids[19],
    title: 'Read chapter 2-4 in course book',
    desc: 'Description of the task',
    type: 'task',
    state: 'todo',
    links: [ids[6]],
    estimate: 1,
  },
  [ids[20]]: {
    id: ids[20],
    title: 'Watch Geeks4Geeks videos',
    desc: 'Description of the task',
    type: 'task',
    state: 'todo',
    links: [ids[6]],
    estimate: 1,
  },
};
